import {
  Key,
  Home,
  Zap,
  Flame,
  Wrench,
  Broom,
  ShoppingBasket,
  Carrot,
  Cookie,
  Milk,
  Bike,
  Rocket,
  Coffee,
  ShoppingBag,
  Car,
  Pill,
  GraduationCap,
  MoreHorizontal,
  Banknote,
  Smartphone,
  CreditCard,
  type LucideIcon,
} from "lucide-react";
import type { Category, PaymentMode } from "./constants";

export const CATEGORY_ICON: Record<Category, LucideIcon> = {
  Rent: Key,
  "Home Essentials": Home,
  "Electricity Bill": Zap,
  Gas: Flame,
  Repairs: Wrench,
  Househelp: Broom,
  Groceries: ShoppingBasket,
  "Veggies & Fruits": Carrot,
  Snacks: Cookie,
  Milk: Milk,
  "Food Delivery": Bike,
  "Blinkit, Zepto": Rocket,
  Hangout: Coffee,
  "Online Shopping": ShoppingBag,
  Rides: Car,
  Medicines: Pill,
  "College Fee": GraduationCap,
  Miscellaneous: MoreHorizontal,
};

// Shades of the Khata accent (navy), darkest to lightest — used for
// chart segments / swatches where categories need to be told apart visually.
export const CATEGORY_CHART_COLOR: Record<Category, string> = {
  Rent: "#16222c",
  "Home Essentials": "#212d37",
  "Electricity Bill": "#2d3842",
  Gas: "#38434c",
  Repairs: "#434e57",
  Househelp: "#4e5962",
  Groceries: "#5a646d",
  "Veggies & Fruits": "#656f78",
  Snacks: "#707a83",
  Milk: "#7c868d",
  "Food Delivery": "#879198",
  "Blinkit, Zepto": "#929ca3",
  Hangout: "#9ea7ae",
  "Online Shopping": "#a9b2b9",
  Rides: "#b4bdc4",
  Medicines: "#bfc8ce",
  "College Fee": "#cbd3d9",
  Miscellaneous: "#d6dee4",
};

export const PAYMENT_ICON: Record<PaymentMode, LucideIcon> = {
  Cash: Banknote,
  UPI: Smartphone,
  Card: CreditCard,
};
